In [6]:
# NumPy Functions
# (a) Array filled with zeroes
ar_zero=np.zeros(4)
print(ar_zero)

ar_zero2=np.zeros((3,4))
print(ar_zero2)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# (b)array filled with ones
ar_one=np.ones(4)
print(ar_one)

ar_one2=np.ones((3,4))
print(ar_one2)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# (c)Empty array
ar_emp=np.empty(5)
print(ar_emp)

[2.12199579e-314 1.16709769e-311 3.65608578e-321 7.75844101e-310
 5.53682373e-317]


In [17]:
# (d)An Array with a range of elements
ar_range=np.arange(4)
print(ar_range)

ar_range2=np.arange(3,8)
print(ar_range2)


[3 4 5 6 7]


In [20]:
# (e)array diagonal filled with ones
ar_dia=np.eye(3)
print(ar_dia)

ar_dia2=np.eye(3,4)
print(ar_dia2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [22]:
# (f) create an array with values that are spaced linearly in a specified interval
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

ar_lin2=np.linspace(0,20,num=5)
print(ar_lin2)


[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  5. 10. 15. 20.]
