In [76]:
# INSERT ELEMENT IN ARRAY
import numpy as np

# insert() func
var=np.array([1,3,7,9])
v=np.insert(var,2,5)
print(var)
print(v)

#append() func
var1=np.array([1,3,7,9])
x=np.append(var,5)
print(var1)
print(x)

[1 3 7 9]
[1 3 5 7 9]
[1 3 7 9]
[1 3 7 9 5]
