In [1]:
# Create an array in Numpy
import numpy as np
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
#Dimensions in Array
ar1=np.array([1,2,3,4])
print(ar1)
print(ar1.ndim)

ar2=np.array([[1,2],[3,4]])
print(ar2)
print(ar2.ndim)

ar3=np.array([[[1,2],[3,4],[5,6]]])
print(ar3)
print(ar3.ndim)

arn=np.array([1,2,3,4],ndmin=8)
print(arn)

[1 2 3 4]
1
[[1 2]
 [3 4]]
2
[[[1 2]
  [3 4]
  [5 6]]]
3
[[[[[[[[1 2 3 4]]]]]]]]
