In [67]:
# JOIN ARRAY
import numpy as np
var=np.array([1,2,3,4])
var2=np.array([6,7,8,9])

arr=np.concatenate((var,var2))
print(arr)

arr1=np.stack((var,var2),axis=0)
print(arr1)

arr2=np.stack((var,var2),axis=1)
print(arr2)

arr3=np.hstack((var,var2))
print(arr3)

arr4=np.vstack((var,var2))
print(arr4)

arr5=np.dstack((var,var2))
print(arr5)


[1 2 3 4 6 7 8 9]
[[1 2 3 4]
 [6 7 8 9]]
[[1 6]
 [2 7]
 [3 8]
 [4 9]]
[1 2 3 4 6 7 8 9]
[[1 2 3 4]
 [6 7 8 9]]
[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [71]:
# SPLIT ARRAY
# splitting array into parts
import numpy as np

var=np.array([[1,2],[3,4],[5,6]])
print(var)
ar1=np.array_split(var,3)
print(ar1)

ar2=np.array_split(var,4,axis=1)
print(ar2)


[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32), array([], shape=(3, 0), dtype=int32)]
