In [ ]:
# create numpy arrays with random numbers
# rand() - random value 0 to 1
# randint()- random number between given range
# randn() - random value close to zero (including -ve values)
# ranf() - random sampling

In [23]:
# rand()

var=np.random.rand(4)
print(var)

[0.61447319 0.86284554 0.92415536 0.49162514]


In [26]:
# randint()
# var2=np.random.randint(min,max,total_values)

var2=np.random.randint(5,20,3)
print(var2)

[10  5 19]


In [27]:
# randn()

var3=np.random.randn(4)
print(var3)

[ 0.53405671 -1.5662359  -1.68253205 -0.93413849]


In [30]:
# ranf()

var4=np.random.ranf(6)
print(var4)

[0.29228334 0.36141987 0.68868084 0.59816968 0.74579021 0.24319412]
